services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    environment:
      - VITE_SERVER_HOST=0.0.0.0
      - VITE_SERVER_PORT=5173
